export default function Head() {
  return (
    <>
      <title>중소기업 ESG컨설팅 | ESG Master</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/favicon.ico" />
    </>
  );
}
